### ISSUE TITLE
About the readme file

### ISSUE THREAD

**Issue by hunterdes** [iconduit/iconduit#87]
Hello, Just need readme file to understand how to use this. At the moment, it's empty

**Comment by ezzatron** [comment]
Whoops, dunno how I missed this comment for so long. Sorry!

The reason why this project doesn't have any documentation at the moment is because I haven't even come close to finalizing how I think it should work yet. I already kind of know it needs a full re-write to be a viable project long-term.

**Comment by hunterdes** [comment]
Thanks boss
